#!/bin/bash

##########STEP 1##########

systemctl stop firewalld
systemctl disable firewalld
rpm -Uvh http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
yum install -y nginx
systemctl start nginx
systemctl start nginx
yum install -y epel-release
rpm -Uhv http://rpms.remirepo.net/enterprise/remi-release-7.rpm
yum install -y yum-utils
yum-config-manager --enable remi-php71
yum install -y php71 php-fpm php-cli php-mysql php-gd php-ldap php-odbc php-pdo php-pecl-memcache php-pear php-xml php-xmlrpc php-mbstring php-snmp php-soap php-bcmath
systemctl start php-fpm
systemctl enable php-fpm

##########STEP 2##########

#/etc/php-fpm.d/www.conf 
#Изменяем строку ;listen = 127.0.0.1:9000 (ставим точку с запятой)
#user = nginx
#group = nginx
echo "listen = /var/run/php-fpm/php-fpm.sock" >> /etc/php-fpm.d/www.conf 
echo "listen.mode = 0660" >> /etc/php-fpm.d/www.conf 
echo "listen.owner = nginx" >> /etc/php-fpm.d/www.conf 
echo "listen.group = nginx" >> /etc/php-fpm.d/www.conf 
systemctl restart php-fpm

##########STEP 3##########

#mcedit /etc/yum.repos.d/mariadb.repo
echo "# MariaDB 10.3 CentOS repository list - created 2018-10-04 12:10 UTC
# http://downloads.mariadb.org/mariadb/repositories/
[mariadb]
name = MariaDB
baseurl = http://yum.mariadb.org/10.3/centos7-amd64
gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
gpgcheck=1" > /etc/yum.repos.d/mariadb.repo

##########STEP 4##########

yum install MariaDB-server MariaDB-client
systemctl start mariadb
systemctl enable mariadb
/usr/bin/mysql_secure_installation

##########STEP 5##########

#mcedit /etc/my.cnf.d/server.cnf
echo "[client]
port		= 3306
socket		= /var/lib/mysql/mysql.sock
default-character-set=utf8

[mysqld]
character_set_server=utf8
collation-server=utf8_bin 
init_connect="SET NAMES utf8 collate utf8_bin"
port = 3306
socket = /var/lib/mysql/mysql.sock
innodb_file_per_table=1 innodb_buffer_pool_size = 768M # внимание на параметр! установить примерно в 2 раза меньше объема оперативной памяти сервера
innodb_buffer_pool_instances=1 # увеличивать на 1 каждый GB
innodb_buffer_pool_size
innodb_flush_log_at_trx_commit = 0
innodb_log_file_size = 512M
innodb_log_files_in_group = 3
innodb-strict-mode = OFF
[server]
[galera]
[embedded]
[mariadb]
[mariadb-10.3]" > /etc/my.cnf.d/server.cnf
